In [1]:
import sympy as sym
import numpy as np
 
from IPython.display import display, Math
from sympy.abc import x, y

In [2]:
x = sym.symbols("x")
# 2*x + 4 - 9 = 0
expr = 2*x + 4 - 9
sym.solve(expr)

[5/2]

In [3]:
display(Math("\\text{The solution to } %s \\text{ is x =} %s " % (sym.latex(expr), sym.latex(sym.solve(expr)))))

<IPython.core.display.Math object>

In [4]:
solutions = sym.solve(x**2 - 4)
print(type(solutions))
print(len(solutions))
solutions

<class 'list'>
2


[-2, 2]

In [5]:
y = sym.symbols('y')
expr = x/4 - x*y + 5
print("Solution for x: " + str(sym.solve(expr, x)[0]))
print("Solution for y: " + str(sym.solve(expr, y)[0]))

Solution for x: 20/(4*y - 1)
Solution for y: (x + 20)/(4*x)


In [6]:
# Exercise 1
q = sym.symbols('q')
expr1 = 3*q + 4/q + 3
expr2 = 5*q + 1/q + 1
simplified = sym.simplify(sym.Eq(expr1, expr2))
for idx, solution in enumerate(sym.solve(simplified)):
  display(Math("\\text{Solution } %g: %s" % (idx + 1, sym.latex(solution))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [7]:
# Exercise 2
q = sym.symbols('q')
expr = 2*q + 3*q**2 - 5/q - 4/q**3
display(Math(sym.latex(sym.simplify(expr))))

<IPython.core.display.Math object>

In [8]:
display(Math(sym.latex(sym.cancel(expr))))

<IPython.core.display.Math object>

In [9]:
# Exercise 3
q = sym.symbols('q')
expr = (sym.sqrt(3) + sym.sqrt(15)*q) / (sym.sqrt(2) + sym.sqrt(10)*q)
for solution in sym.solve(expr, q, 10):
  display(Math('%s = %s' % (sym.latex(expr), sym.latex(solution))))

display(Math('%s = %s' % (sym.latex(expr), sym.latex(expr.subs(q, 10).evalf()))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [10]:
from sympy.abc import x

term1 = (4*x + 5)
term2 = x
term3 = x-7

display(Math(sym.latex(term1 * term2)))
display(Math(sym.latex(sym.expand(term1*term2))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [11]:
term3 = x-7
display(Math(sym.latex(term1*term3)))
display(Math(sym.latex(sym.expand(term1*term3))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [12]:
from sympy.abc import y

expr = x*(2*y**2 - 5**x/x)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.expand(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [13]:
%whos

Variable     Type        Data/Info
----------------------------------
Math         type        <class 'IPython.core.display.Math'>
display      function    <function display at 0x7f74197cd200>
expr         Mul         x*(-5**x/x + 2*y**2)
expr1        Add         3*q + 3 + 4/q
expr2        Add         5*q + 1 + 1/q
idx          int         1
np           module      <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
q            Symbol      q
simplified   Equality    Eq(5*q + 1 + 1/q, 3*q + 3 + 4/q)
solution     tuple       n=2
solutions    list        n=2
sym          module      <module 'sympy' from '/us<...>kages/sympy/__init__.py'>
term1        Add         4*x + 5
term2        Symbol      x
term3        Add         x - 7
x            Symbol      x
y            Symbol      y


In [14]:
# Exercise

x, y = sym.symbols("x,y")
Fxy = (4+x)*(2-y)

display(Math('\\text{f(x, y) = } %s' % (sym.latex(expr))))
for xi in range(3):
  for yi in range(3):
    result = Fxy.subs({
      x: xi,
      y: yi
    })
    print(f"When x={xi} and y={yi}, f(x,y)={result}")

<IPython.core.display.Math object>

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


In [15]:
A = np.array([[1, 2], [3, 4]])
print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [16]:
matrix = np.zeros([4, 6])
matrix[0, 1] = 2
matrix[2, 4] = 7
print(matrix)
display(Math(sym.latex(sym.sympify(matrix))))

[[0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 0.]]


<IPython.core.display.Math object>

In [17]:
# Exercise

matrix = np.zeros((3, 3))
x, y = sym.symbols("x,y")
Fxy = (4+x) * (2-y)
for xi in range(3):
  for yi in range(3):
    matrix[xi, yi] = Fxy.subs({
        x: xi,
        y: yi
    })
display(Math(sym.latex(sym.sympify(matrix))))

<IPython.core.display.Math object>

In [18]:
# Exercise: Create a multiplication table

numbers = range(1, 11)
matrix = np.zeros((len(numbers), len(numbers)), dtype=int)
for xi in numbers:
  for yi in numbers:
    matrix[xi - 1, yi - 1] = xi * yi
display(Math(sym.latex(sym.sympify(matrix))))

<IPython.core.display.Math object>

In [19]:
# Associative

expr1 = x*(4*y)
expr2 = (x*4)*y

expr1 - expr2

0

In [20]:
# Commutative

expr1 = 4*x*y
expr2 = x*4*y
expr3 = y*x*4
print(expr1.subs({ x: 3, y: 2 }))
print(expr2.subs({ x: 3, y: 2 }))
print(expr3.subs({ x: 3, y: 2 }))

24
24
24


In [21]:
# Distributive
a, b, c, d = sym.symbols("a,b,c,d")

expr1 = (a+b)*(c+d)
sym.expand(expr1)

a*c + a*d + b*c + b*d

In [22]:
# Exercises
from sympy.abc import x, y, w, z

x = w * (4-w) + 1/w**2 *(1 + w)
f1 = x*(y+z)
f2 = 3/x + x**2

display(Math(sym.latex(f1*f2)))
display(Math(sym.latex(sym.simplify(f1*f2))))
display(Math(sym.latex(sym.simplify(f1*f2 - f2*f1))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [23]:
x = sym.symbols("x")

expr1 = 2*x + x*(4-6*x) + x
expr2 = -x * (2/x + 4/x**2) + (4+x)/(4*x)
expr3 = (x+3)*(x-3)*x*(1/(9*x))
exprs = [expr1, expr2, expr3]

for expr in exprs:
  display(Math("%s \\quad \\Longleftrightarrow \\quad %s" % (sym.latex(expr), sym.latex(sym.expand(expr)))))
  print()

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [24]:
import math

print(math.gcd(6, 15))
print(math.gcd(4, 16))  

3
4


In [25]:
a = 16
b = 88

factor = math.gcd(a, b)

display(Math('\\frac{%g}{%g} = \\frac{%g\\times %g}{%g\\times %g}' % (a, b, a/factor, factor, b/factor, factor)))

<IPython.core.display.Math object>

In [26]:
# Exercise 1

a, b, c = sym.symbols("a,b,c")
f = sym.gcd(c*a, c*b)
g = c*sym.gcd(a, b)
sym.Eq(f, g)

True

In [27]:
print(f.subs({
    a: 2,
    b: 5,
    c: 7
}))

print(g.subs({
    a: 2,
    b: 5,
    c: 7  
}))

7
7


In [28]:
# Exercise 2

matrix = np.zeros((15, 10), dtype=int) + 99
for i in range(matrix.shape[0]):
  for j in range(matrix.shape[1]):
    matrix[i, j] = math.gcd(i+1, j+1)
display(Math(sym.latex(sym.sympify(matrix))))

<IPython.core.display.Math object>

In [29]:
x, y = sym.symbols("x,y")

dict_equation = dict(eqs_with_x = [4*x-6, x**2-9], eqs_with_y = [sym.sin(y)])

for keyi in dict_equation:
  print(f"Solutions for equations involving {keyi[-1]}:")
  for equation in dict_equation[keyi]:
    left_part = sym.latex(equation) + " = 0"
    mid_part = "\\quad \\Rightarrow \\quad " + keyi[-1] + " = "
    right_part = sym.latex(sym.solve(equation))

    display(Math('\\quad\\quad ' + left_part + mid_part + right_part))

Solutions for equations involving x:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

Solutions for equations involving y:


<IPython.core.display.Math object>

In [30]:
number = 48

sym.factorint(number)

{2: 4, 3: 1}

In [31]:
# Exercise

for i in range(2, 51):
  dict_factor = sym.factorint(i)
  if len(dict_factor) == 1 and list(dict_factor.values())[0] == 1:
    print(f"{i} is a prime number")
  else:
    print(f"{i} is a composite number with prime factors {list(dict_factor.keys())}")

2 is a prime number
3 is a prime number
4 is a composite number with prime factors [2]
5 is a prime number
6 is a composite number with prime factors [2, 3]
7 is a prime number
8 is a composite number with prime factors [2]
9 is a composite number with prime factors [3]
10 is a composite number with prime factors [2, 5]
11 is a prime number
12 is a composite number with prime factors [2, 3]
13 is a prime number
14 is a composite number with prime factors [2, 7]
15 is a composite number with prime factors [3, 5]
16 is a composite number with prime factors [2]
17 is a prime number
18 is a composite number with prime factors [2, 3]
19 is a prime number
20 is a composite number with prime factors [2, 5]
21 is a composite number with prime factors [3, 7]
22 is a composite number with prime factors [2, 11]
23 is a prime number
24 is a composite number with prime factors [2, 3]
25 is a composite number with prime factors [5]
26 is a composite number with prime factors [2, 13]
27 is a composit

In [32]:
x = sym.symbols("x")

expr = 4*x > 8
sym.solve(expr)

(2 < x) & (x < oo)

In [33]:
expr = (x-1) * (x+3) > 0
sym.solve(expr)

((-oo < x) & (x < -3)) | ((1 < x) & (x < oo))

In [34]:
a,b,c = sym.symbols("a,b,c")
expr = a*x > b**2/c
display(Math(sym.latex(expr)))

<IPython.core.display.Math object>

In [35]:
x = sym.symbols("x")
expr = 3*x/2 + (4-5*x)/3 <= 2 - (5*(2-x))/4
display(Math(sym.latex(expr)))
sym.solve(expr, x)

<IPython.core.display.Math object>

(22/17 <= x) & (x < oo)

In [36]:
from sympy.abc import x

p1 = 2*x**3 + x**2 - x
p2 = x**3 - x**4 - 4*x**2

display(Math(sym.latex(p1)))
display(Math(sym.latex(p2)))
display(Math("(%s) + (%s) = %s" % (sym.latex(p1), sym.latex(p2), sym.latex(p1+p2))))
display(Math("(%s) - (%s) = %s" % (sym.latex(p1), sym.latex(p2), sym.latex(p1-p2))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [37]:
p1 = sym.Poly(2*x**3 + x**2 - x)
print(p1)

Poly(2*x**3 + x**2 - x, x, domain='ZZ')


In [38]:
p1.eval(0)

0

In [39]:
p1.coeffs()

[2, 1, -1]

In [40]:
# Exercise

equations = [(x**2 + 2*x), (-x**3 + 4*x), (x**5 - x**4 + x/4 + 4)]
for equation in equations:
  poly = equation.as_poly()
  if poly.degree() % 2 == 0:
    display(Math("\\text{The degree of } \\Rightarrow %s \\text{ is even, and the coefficients sum is } %g" % (sym.latex(poly.as_expr()), sum(poly.coeffs()))))
  else:
    display(Math("\\text{The degree of } \\Rightarrow %s \\text{ is odd, and the coefficients count is } %g" % (sym.latex(poly.as_expr()), len(poly.coeffs()))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [41]:
x = sym.symbols("x")

expr = x**5 * x**3
expr

x**8

In [42]:
p1 = 4*x**2 - 2*x
p2 = x**3 - 1

display(Math(sym.latex(p1*p2)))
display(Math(sym.latex(sym.expand(p1*p2))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [43]:
# Exercise
x, y = sym.symbols("x,y")
f_xy = 4*x**4 - 3*x**2 + x*y**2 - 9*y**3
g_xy = -x**3 + 6*x**2*y + 0.8*y**3

parameters = {
    x: 5,
    y: -2
}

display(Math(sym.latex(f_xy * g_xy)))
display(Math(sym.latex(sym.expand(f_xy * g_xy))))
display(Math(sym.latex(sym.expand(f_xy * g_xy).subs(parameters))))
display(Math(sym.latex(sym.expand(f_xy.subs(parameters) * g_xy.subs(parameters)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [44]:
x = sym.symbols("x")

p1 = 4*x**5 - x
p2 = 2*x**3 - x

display(Math("\\frac{%s}{%s} = %s" % (sym.latex(p1), sym.latex(p2), sym.latex(p1 / p2))))
display(Math("\\frac{%s}{%s} = %s" % (sym.latex(p1), sym.latex(p2), sym.latex(sym.expand(p1 / p2)))))
display(Math("\\frac{%s}{%s} = %s" % (sym.latex(p1), sym.latex(p2), sym.latex(sym.simplify(p1 / p2)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [60]:
x, y = sym.symbols("x,y")

poly_numerator = (x**6 + 2*x**4 + 6*x - y)
poly_denominator = (x**3+3)
display(Math(sym.latex(poly_numerator/poly_denominator)))

right_answer = None
for yi in range(5, 16):
  poly_numerator_yi = poly_numerator.subs(y, yi)
  equation = poly_numerator_yi/poly_denominator
  equation_simplified = sym.simplify(poly_numerator_yi/poly_denominator)
  display(Math('%s = %s' % (sym.latex(equation), sym.latex(equation_simplified))))
  if sym.fraction(sym.simplify(poly_numerator_yi/poly_denominator))[1] == 1:
    right_answer = yi

if right_answer:
  print(f"\nThe answer that satisfies our goal is y = {right_answer}")

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>


The answer that satisfies our goal is y = 9


In [63]:
x, y = sym.symbols("x,y")

equation = x**2 + 4*x + 3
display(Math('%s = %s' % (sym.latex(equation), sym.latex(sym.factor(equation)))))

equation = x**2 + 4*x - 3
display(Math('%s = %s' % (sym.latex(equation), sym.latex(sym.factor(equation)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [64]:
expr = 2*x**3*y - 2*x**2 + 2*x**2*y + 6*x**2 - 6*x*y + 6*x
sym.factor(expr)

2*x*(x**2*y + x*y + 2*x - 3*y + 3)

In [69]:
expressions = [x**2 + 4*x + 3, 2*y**2 - 1, 3*y**2 + 12*y]


for expr in expressions:
  factor = sym.factor(expr)
  factorable = "(" in str(factor)
  if factorable:
    display(Math('%s \\quad \\Rightarrow \\quad %s' % (sym.latex(expr), sym.latex(simplified))))
  else:
    display(Math('%s \\quad \\Rightarrow \\quad \\text{not factorable}' % (sym.latex(expr))))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

# **BUG HUNT!**

In [99]:
import sympy as sym


x2 = sym.symbols("x2")
x2 = 4
x2

4

In [77]:
a, b, c = sym.symbols("a,b,c")
expr = 4*b + 5*a*a - c**3 + 5*d

In [79]:
import math

math.gcd(30, 50)

10

In [81]:
expr = 4*x - 8
sym.solve(expr)

[2]

In [84]:
import numpy as np


A = np.array([[1, 2], [3, 4]])
# make it look nice
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [86]:
fact_dict = sym.factorint(44)
allkeys = fact_dict.keys()

keys = list(allkeys)
for i in range(0, len(keys)):
  print('%g was present %g times.' % (i, keys[i]))

0 was present 2 times.
1 was present 11 times.


In [88]:
x, y = sym.symbols("x,y")

expr = 4*x - 5*y**2
expr.subs({x: 5})

20 - 5*y**2

In [91]:
# goal is to show a fraction

f = sym.sympify(5)/9
display(Math(sym.latex(f)))

<IPython.core.display.Math object>

In [100]:
# print the last 3 items from a list
lst = [1, 3, 2, 5, 4, 6, 7, 5, 3, 7]
lst[-3:]

[5, 3, 7]

In [98]:
from sympy.abc import x, y

expr = 2*x + 4*y

# solve for y
sym.solve(expr, y)[0]

-x/2

In [103]:
import numpy as np


A = np.array([[1, 2], [3, 4]])

# set the element in the second row, second column to 9
A[1, 1] = 9
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>